# Generated by Django 3.1.1 on 2022-03-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OmsOrderImportBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.IntegerField(blank=True, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('warehouse_code', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_code', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_method', models.CharField(blank=True, max_length=45, null=True)),
                ('sales_platform', models.CharField(blank=True, max_length=45, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=45, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=255, null=True)),
                ('label_tracking_number', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('consignee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('consignee_company', models.CharField(blank=True, max_length=100, null=True)),
                ('consignee_country', models.CharField(blank=True, max_length=45, null=True)),
                ('consignee_state', models.CharField(blank=True, max_length=45, null=True)),
                ('consignee_city', models.CharField(blank=True, max_length=100, null=True)),
                ('consignee_street', models.CharField(blank=True, max_length=255, null=True)),
                ('consignee_street2', models.CharField(blank=True, max_length=255, null=True)),
                ('consignee_zipcode', models.CharField(blank=True, max_length=45, null=True)),
                ('consignee_email', models.CharField(blank=True, max_length=155, null=True)),
                ('consignee_phone', models.CharField(blank=True, max_length=45, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('is_order_box', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'oms_order_import_batch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OmsOrderProductImportBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.IntegerField(blank=True, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=155, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=155, null=True)),
                ('declared_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('username', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'oms_order_product_import_batch',
                'managed': False,
            },
        ),
    ]
