# Generated by Django 4.1.5 on 2025-07-09 16:16

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CheckInTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_identifier",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique URL for driver waiting page",
                        unique=True,
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[("PICKUP", "Pickup"), ("DROP", "Drop Trailer")],
                        max_length=10,
                        verbose_name="Ticket Type",
                    ),
                ),
                (
                    "driver_name",
                    models.CharField(max_length=100, verbose_name="Driver's Name"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="Company Name"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Phone Number"),
                ),
                (
                    "po_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="PO Number"
                    ),
                ),
                (
                    "trailer_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Trailer/Container Number",
                    ),
                ),
                (
                    "drivers_license_image",
                    models.ImageField(
                        upload_to="licenses/", verbose_name="Driver's License Photo"
                    ),
                ),
                (
                    "bol_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="bols/",
                        verbose_name="Bill of Lading (BOL) Photo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ASSIGNED", "Assigned"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Ticket Status",
                    ),
                ),
                (
                    "dock_number",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Assigned Dock Number",
                    ),
                ),
                (
                    "check_in_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Check-in Time"
                    ),
                ),
                (
                    "assignment_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Assignment Time"
                    ),
                ),
                (
                    "completion_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completion Time"
                    ),
                ),
            ],
            options={
                "verbose_name": "Check-in Ticket",
                "verbose_name_plural": "Check-in Tickets",
                "ordering": ["-check_in_time"],
            },
        ),
    ]
