# Generated by Django 4.1.5 on 2025-08-27 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TicketApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LtlStorageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picking_no",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="拣货单号"
                    ),
                ),
                (
                    "bol_no",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="BOL单号"
                    ),
                ),
                ("pallet_qty", models.PositiveIntegerField(verbose_name="托盘数量")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("sent", "Sent")],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="备注")),
                ("operator", models.CharField(max_length=50, verbose_name="操作员")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上架时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提货时间"
                    ),
                ),
            ],
            options={
                "db_table": "ltl_storage_record",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("sent", "Sent"),
                        ],
                        max_length=50,
                        verbose_name="操作动作",
                    ),
                ),
                ("operator", models.CharField(max_length=50, verbose_name="操作员")),
                ("note", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="TicketApp.ltlstoragerecord",
                        verbose_name="关联记录",
                    ),
                ),
            ],
            options={
                "db_table": "operation_log",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="WarehouseLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_code",
                    models.CharField(max_length=50, unique=True, verbose_name="库位号"),
                ),
                (
                    "zone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="区域"
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="最大托盘数"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("available", "Available"), ("occupied", "Occupied")],
                        default="available",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "db_table": "warehouse_location",
                "managed": True,
            },
        ),
        migrations.DeleteModel(
            name="CheckInTicket",
        ),
        migrations.AddField(
            model_name="ltlstoragerecord",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ltl_records",
                to="TicketApp.warehouselocation",
                verbose_name="库位",
            ),
        ),
    ]
