# Generated by Django 3.1.1 on 2022-03-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('fullname', models.CharField(blank=True, db_column='FullName', max_length=50, null=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(db_column='Email', max_length=100)),
                ('updates', models.IntegerField(blank=True, db_column='Updates', null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('newuser', models.IntegerField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, db_column='IP', max_length=250, null=True)),
                ('lunch', models.IntegerField(blank=True, default=0, null=True)),
                ('ext', models.CharField(blank=True, max_length=3, null=True)),
                ('emailpassword', models.CharField(blank=True, db_column='EmailPassword', max_length=10, null=True)),
                ('windowslogin', models.CharField(blank=True, db_column='WindowsLogin', max_length=30, null=True)),
                ('profitshare', models.IntegerField(db_column='profitShare', default=0)),
                ('location', models.CharField(blank=True, db_column='location', max_length=45, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
